### ISSUE TITLE
isRouterLink="true"之后报错

### ISSUE THREAD

**Issue by hiseab** [lfyfly/vue-waterfall-easy#13]
Invalid prop: type check failed for prop "to". Expected String, Object, got Boolean

**Comment by hiseab** [comment]
谢谢回复,我用的是例子里的data-router-link.json的数据啊,也报错  
{
    "src": "./static/img/1.jpg",
    "href": "/test",
    "info": "一些图片描述文字"
  },

**Comment by lfyfly** [comment]
是我的问题，已经在 vue-waterfall-easy@2.1.5 修复了，你更新下试试

**Comment by hiseab** [comment]
更新了,但是 我这样:isRouterLink="true" :linkRange="img" 还是报错:
[Vue warn]: Property or method "img" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property

**Comment by lfyfly** [comment]
`linkRange` 是`String`类型啊,不需要加冒号

**Comment by lyh2** [comment]
自定义跳转问题，添加@click事件也是成功的。但是返回的时候，中间多了一个页面，也就是a标签跳转的页面？怎么解决？
