### ISSUE TITLE
建议 height 属性更灵活点

### ISSUE THREAD

**Issue by zaxlct** [lfyfly/vue-waterfall-easy#15]
看了源码，height 只能传递数字（实际单位是像素），有点不方便。
可能有的需求是想设置 90vh，或者 100rem ，或者 calc(100vh - 200px)

**Comment by lfyfly** [comment]
vue-waterfall-easy@2.1.7 [对`height`属性新增一个`String`类型](https://github.com/lfyfly/vue-waterfall-easy/blob/master/README-CN.md#3-组件参数)，可以自己传单位。
