### ISSUE TITLE
img error

### ISSUE THREAD

**Issue by carboyDing** [lfyfly/vue-waterfall-easy#16]
请问下图片加载失败的情况，图片的高度怎么算的

**Comment by lfyfly** [comment]
![k_l91gqhobu6 q x 1 zdr3](https://user-images.githubusercontent.com/21997532/41288717-e228b662-6e79-11e8-91a8-019087cd4704.png)

**Comment by carboyDing** [comment]
后面可以考虑做一个图片错误的配置项，包含错误图片的高度和URL，这样会更完美一点

**Comment by lfyfly** [comment]
我也在考虑做一张默认的错误图片

**Comment by lfyfly** [comment]
![默认错误图片](https://user-images.githubusercontent.com/21997532/42460546-bc35b0a6-83d0-11e8-90a2-c8e04a3e532a.png)

**Comment by carboyDing** [comment]
赞
