### ISSUE TITLE
PROP的imgsArr默认值要用函数返回。 

### ISSUE THREAD

**Issue by cute001** [lfyfly/vue-waterfall-easy#17]
Invalid default value for prop "imgsArr": Props with type Object/Array must use a factory function to return the default value.
官方文档写的：
// 对象或数组且一定会从一个工厂函数返回默认值

imgsArr和loadingDotStyle必须用函数返回。
`loadingDotStyle: {
      type: Object,
      default: function () {
        return null;
      }
    },`
`imgsArr: {
      type: Array,
      required: true,
      default: function () {
        return [];
      }
    },`

**Comment by lfyfly** [comment]
你说的是对的，我会改正的
