### ISSUE TITLE
使用相对定位，如果图集是对齐的，无法触发图片到底部自动更新的操作

### ISSUE THREAD

**Issue by libp** [lfyfly/vue-waterfall-easy#27]
使用相对定位，如果图集是对齐的，无法触发图片到底部自动更新的操作，如这个链接下是一个图集，
总共有90张照片，每次加载10张，加载到第2次后，后面无法再加载
https://www.nichuiniu.cn/wanhg/imgnum/486

**Comment by lfyfly** [comment]
[给`reachBottomDistance`一个值试试](https://github.com/lfyfly/vue-waterfall-easy/blob/master/README-CN.md#3-组件参数)

**Comment by lfyfly** [comment]
我测了下没什么问题，你clone这个项目，改变`static/mock/data.json`数组使所有元素都相同，在`src/App.vue`里vue-waterfall-easy组件添加 `reachBottomDistance`属性，测试一下

**Comment by libp** [comment]
我试了，第一额问题解决了。只是显示不全不知道是什么原因。如：https://www.nichuiniu.cn/wanhg/imgnum/486

**Comment by libp** [comment]
最后几张图片还有约10分之1没出来。

**Comment by lfyfly** [comment]
你布局有问题,waterfall 高度超出 `.content`了

**Comment by libp** [comment]
<img width="219" alt="_20180723070432" src="https://user-images.githubusercontent.com/16248888/43051105-ae4b9ce6-8e46-11e8-854c-5288f4844f00.png">
`.content`高度设置为100%时，如图会出现两个滚动条。
非常感谢

**Comment by lfyfly** [comment]
vue-waterfall-easy组件的宽高默认为父元素的100%，所以其父元素（你这就是.content）不允许有其他子元素
。
