### ISSUE TITLE
怎麼設置圖片的寬度？

### ISSUE THREAD

**Issue by hwxhehe2793** [lfyfly/vue-waterfall-easy#30]
大佬設置圖片寬度怎麼沒起效果？求教一下，謝謝。
 <vueWaterfallEasy :imgsArr="imgsArr" :imgWidth="imgsWidth"></vueWaterfallEasy>
data() {
    return {
      //圖片大小
      imgsWidth: 80, ｝

**Comment by hwxhehe2793** [comment]
<vueWaterfallEasy :imgsArr="imgsArr" :imgWidth="imgsWidth"></vueWaterfallEasy>

**Comment by lfyfly** [comment]
移动端自动两列，铺满屏幕宽度。

**Comment by hwxhehe2793** [comment]
好的 謝謝
