### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by pookpal** [lfyfly/vue-waterfall-easy#31]
滚动触底事件中有个小bug，部分极端高度下会发生，需要将判断条件修改下
![image](https://user-images.githubusercontent.com/10249353/43672951-308a275a-97ec-11e8-8c4b-c78d1c1260ab.png)

**Comment by lfyfly** [comment]
好的

**Comment by whmmm** [comment]
@lfyfly  能不能说下具体改哪里呢..我也遇到了这个问题,在特定高度下,还没有达到底部,但是整个页面却无法滚动---.
我没有用 webpack... 想请教一下,

**Comment by lfyfly** [comment]
@whmmm 加上面这个属性试试
`:reachBottomDistance="30"`
