### ISSUE TITLE
没有图片，没有href，只有文字，自定义点击跳转

### ISSUE THREAD

**Issue by jlcool** [lfyfly/vue-waterfall-easy#37]
没有图片，没有href，只有文字，自定义点击跳转，怎么用

**Comment by jlcool** [comment]
具体怎么用呢，这文档写的不太清楚啊

**Comment by lfyfly** [comment]
和有图的时候一样用，会自动识别是数据中否有图片链接。
自定义跳转可以通过`vue-waterfall-easy`的 click事件实现

**Comment by jlcool** [comment]
没设置容器高度，容器高度怎么自适应啊

**Comment by lfyfly** [comment]
渲染完之后再获取高度
