### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ttly20** [lfyfly/vue-waterfall-easy#44]
我在使用这个插件的时候遇到这个错误，已经好多天了，一直解决不了。
这是我的代码：
        <script>
            new Vue({
                el: "#app",
                components: {
                    vueWaterfallEasy
                },
                data() {
                    return {
                        imgsArr: [],
                        fechImgsArr: [],
                        group: 1,
                    }
                },
                methods: {
                    getData () {
                        axios.get("http://122.114.227.186:8080/" + this.group)
                            .then(res => {
                                this.imgsArr = res.data
                                this.group++
                                console.log(res.data)
                            })
                    },
                },
                created() {
                        this.getData()
                }
         })
        </script>
这是我的后端返回的json：
![image](https://user-images.githubusercontent.com/20431764/47033433-5f18bb00-d1a7-11e8-827e-e0102e2bc860.png)
这是chrome console下的结果：
![image](https://user-images.githubusercontent.com/20431764/47034359-bfa8f780-d1a9-11e8-9264-66d3fac42ead.png)
可以看到res.data是有Array(0)属性的。
我查了很久的google,不管是用for in重组数组还是重写后端返回的json都解决不了这个问题，我很烦恼，各位大大能帮忙看一下吗？

**Comment by lfyfly** [comment]
可以直接复制源码目录下的vue组件进行调试

**Comment by benzun** [comment]
我是用浏览器加载方式，使用也是报这个错误
