### ISSUE TITLE
图片手机上显示有问题？

### ISSUE THREAD

**Issue by fg607** [lfyfly/vue-waterfall-easy#51]
![1334788535](https://user-images.githubusercontent.com/10409970/47918758-70243480-dee8-11e8-9c73-738d39b72b82.jpg)
图片宽度超出卡片宽度

**Comment by lfyfly** [comment]
https://lfyfly.github.io/vue-waterfall-easy/demo/#/
跑我的demo有问题吗

**Comment by fg607** [comment]
![1434446054](https://user-images.githubusercontent.com/10409970/47948441-50ceeb00-df6c-11e8-8565-1dea2becaf30.jpg)
你的demo没问题，我再看看咋回事，电脑上没毛病

**Comment by fg607** [comment]
@lfyfly 加上  *{margin:0;padding:0} 问题解决了，组价很不错，加油！
