### ISSUE TITLE
相对路径图片引用不成功

### ISSUE THREAD

**Issue by Ann-Cyq** [lfyfly/vue-waterfall-easy#6]
1.vue-cli创建的项目，我把图片放到src里面  展示不了图片，放到static里面就可以，是怎么回事呢
2. 还有info怎么去掉  我在页面内重写了css，覆盖不了

**Comment by lfyfly** [comment]
1.只能使用绝对路径，因为路径是直接用来图片预加载的
2. css样式覆盖，只要更高的css选择器权重，或用 !important

**Comment by Ann-Cyq** [comment]
好的好的 可是css真的没看明白是怎么回事，我在vue-waterfall-easy这个组件定义了个id--waterfall，  然后在style中 #waterfall .img-info{ display: none; },  但是不起作用，不知道为什么，这样子可以吗
