### ISSUE TITLE
How to handle the clicking event callback in the internal photo?

### ISSUE THREAD

**Issue by Ann-Cyq** [lfyfly/vue-waterfall-easy#7]
How to handle the clicking event callback in the internal photo?

**Comment by lfyfly** [comment]
- updated click event on vue-waterfall-easy@2.0.6
- you can update vue-waterfall-easy now
- you can see demo on [README.md](https://github.com/lfyfly/vue-waterfall-easy#4-event)

**Comment by Ann-Cyq** [comment]
I see, thanks!
